# GitHub Actions workflow for PR validation
name: Validate Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'gitops/**'
      - 'policies/**'
      - 'helm-charts/**'
      - 'terraform/**'
      - 'management-cluster/**'

env:
  KUBECONFORM_VERSION: v0.6.4
  KYVERNO_VERSION: v1.11.0

jobs:
  validate-yaml:
    name: Validate YAML Syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate YAML files
        run: |
          pip install pyyaml
          find . -type f \( -name "*.yaml" -o -name "*.yml" \) \
            -not -path "./.git/*" \
            -exec python3 -c "import yaml; yaml.safe_load(open('{}'))" \;

  validate-kubernetes:
    name: Validate Kubernetes Manifests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install kubeconform
        run: |
          curl -sSL "https://github.com/yannh/kubeconform/releases/download/${KUBECONFORM_VERSION}/kubeconform-linux-amd64.tar.gz" | \
          tar xzf - -C /usr/local/bin

      - name: Validate Kubernetes manifests
        run: |
          find . -type f \( -name "*.yaml" -o -name "*.yml" \) \
            -not -path "./.git/*" \
            -not -path "./terraform/*" \
            -not -name "kustomization.yaml" \
            -not -name "Chart.yaml" \
            -not -name "values*.yaml" \
            -exec kubeconform -strict -ignore-missing-schemas {} \;

  validate-kyverno:
    name: Validate Kyverno Policies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Kyverno CLI
        run: |
          curl -sSL "https://github.com/kyverno/kyverno/releases/download/${KYVERNO_VERSION}/kyverno-cli_${KYVERNO_VERSION}_linux_x86_64.tar.gz" | \
          tar xzf - -C /usr/local/bin kyverno

      - name: Validate Kyverno policies
        run: |
          kyverno validate policies/kyverno/

  validate-helm:
    name: Validate Helm Charts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Lint Helm charts
        run: |
          for chart in helm-charts/*/; do
            if [ -f "${chart}Chart.yaml" ]; then
              echo "Linting $chart"
              helm lint "$chart"
            fi
          done

  validate-terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Format Check
        run: terraform fmt -check -recursive terraform/

      - name: Terraform Validate
        run: |
          for dir in terraform/modules/*/; do
            echo "Validating $dir"
            terraform -chdir="$dir" init -backend=false
            terraform -chdir="$dir" validate
          done

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  policy-test:
    name: Test Policies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Kyverno CLI
        run: |
          curl -sSL "https://github.com/kyverno/kyverno/releases/download/${KYVERNO_VERSION}/kyverno-cli_${KYVERNO_VERSION}_linux_x86_64.tar.gz" | \
          tar xzf - -C /usr/local/bin kyverno

      - name: Test policies against sample resources
        run: |
          if [ -d "policies/kyverno/tests" ]; then
            kyverno test policies/kyverno/tests/
          else
            echo "No policy tests found, skipping"
          fi

  flux-diff:
    name: Flux Diff
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main

      - name: Generate diff
        id: diff
        run: |
          # Compare Kustomization outputs between base and head
          echo "## Flux Diff" >> $GITHUB_STEP_SUMMARY
          echo "Changes detected in GitOps configurations" >> $GITHUB_STEP_SUMMARY

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## GitOps Validation Passed\n\nAll validation checks have passed. Ready for review.'
            })
