---
# Composite Resource Definition for Kubernetes Clusters
# This XRD provides a cloud-agnostic API for provisioning Kubernetes clusters
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xkubernetesclusters.platform.gitops.io
  annotations:
    description: |
      A Kubernetes cluster abstraction that works across AWS (EKS),
      GCP (GKE), and Azure (AKS). Platform teams can use this to
      provision production-ready clusters with a single API.
spec:
  group: platform.gitops.io
  names:
    kind: XKubernetesCluster
    plural: xkubernetesclusters
    shortNames:
      - xk8s
      - xcluster
    categories:
      - crossplane
      - platform
      - kubernetes

  claimNames:
    kind: KubernetesCluster
    plural: kubernetesclusters

  connectionSecretKeys:
    - kubeconfig
    - cluster-ca
    - cluster-endpoint
    - cluster-token

  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "Specification for the Kubernetes cluster"
              required:
                - cloudProvider
                - region
                - environment
              properties:
                # Cloud Provider Selection
                cloudProvider:
                  type: string
                  description: "Target cloud provider"
                  enum:
                    - aws
                    - gcp
                    - azure
                  default: aws

                # Region Configuration
                region:
                  type: string
                  description: "Cloud region for the cluster"
                  examples:
                    - us-east-1
                    - eu-west-1
                    - us-central1
                    - westeurope

                # Environment Type
                environment:
                  type: string
                  description: "Deployment environment"
                  enum:
                    - development
                    - staging
                    - production
                  default: development

                # Kubernetes Configuration
                kubernetes:
                  type: object
                  description: "Kubernetes cluster configuration"
                  properties:
                    version:
                      type: string
                      description: "Kubernetes version"
                      default: "1.28"
                      pattern: "^[0-9]+\\.[0-9]+$"

                    # Logging and monitoring
                    enableLogging:
                      type: boolean
                      default: true

                    enableSecretEncryption:
                      type: boolean
                      default: true

                    # API Server configuration
                    apiServerAccess:
                      type: string
                      enum:
                        - public
                        - private
                        - public-and-private
                      default: public-and-private

                # Node Groups
                nodeGroups:
                  type: array
                  description: "Worker node group configurations"
                  minItems: 1
                  items:
                    type: object
                    required:
                      - name
                      - instanceType
                      - minSize
                      - maxSize
                    properties:
                      name:
                        type: string
                        description: "Name of the node group"
                        minLength: 1
                        maxLength: 63

                      instanceType:
                        type: string
                        description: "Instance type for nodes"
                        examples:
                          - m6i.xlarge
                          - n2-standard-4
                          - Standard_D4s_v3

                      minSize:
                        type: integer
                        description: "Minimum number of nodes"
                        minimum: 0
                        default: 1

                      maxSize:
                        type: integer
                        description: "Maximum number of nodes"
                        minimum: 1
                        default: 10

                      desiredSize:
                        type: integer
                        description: "Desired number of nodes"
                        minimum: 0

                      diskSizeGb:
                        type: integer
                        description: "Root disk size in GB"
                        default: 100
                        minimum: 20

                      labels:
                        type: object
                        description: "Node labels"
                        additionalProperties:
                          type: string

                      taints:
                        type: array
                        description: "Node taints"
                        items:
                          type: object
                          properties:
                            key:
                              type: string
                            value:
                              type: string
                            effect:
                              type: string
                              enum:
                                - NoSchedule
                                - PreferNoSchedule
                                - NoExecute

                      # Spot/Preemptible instances
                      spotInstances:
                        type: boolean
                        default: false

                # Networking Configuration
                networking:
                  type: object
                  description: "Network configuration"
                  properties:
                    vpcCidr:
                      type: string
                      description: "VPC CIDR block"
                      default: "10.0.0.0/16"
                      pattern: "^([0-9]{1,3}\\.){3}[0-9]{1,3}/[0-9]{1,2}$"

                    podCidr:
                      type: string
                      description: "Pod CIDR block"
                      default: "10.244.0.0/16"

                    serviceCidr:
                      type: string
                      description: "Service CIDR block"
                      default: "10.96.0.0/16"

                    # Network policy engine
                    networkPolicy:
                      type: string
                      enum:
                        - calico
                        - cilium
                        - none
                      default: calico

                # Add-ons Configuration
                addons:
                  type: array
                  description: "Cluster add-ons to install"
                  items:
                    type: string
                    enum:
                      - cluster-autoscaler
                      - metrics-server
                      - aws-ebs-csi-driver
                      - aws-efs-csi-driver
                      - aws-load-balancer-controller
                      - external-dns
                      - cert-manager
                      - ingress-nginx
                      - gcp-pd-csi-driver
                      - azure-disk-csi-driver

                # Tags/Labels for cloud resources
                tags:
                  type: object
                  description: "Tags to apply to all resources"
                  additionalProperties:
                    type: string

                # Maintenance Configuration
                maintenance:
                  type: object
                  description: "Maintenance window configuration"
                  properties:
                    autoUpgrade:
                      type: boolean
                      default: false

                    maintenanceWindow:
                      type: object
                      properties:
                        dayOfWeek:
                          type: string
                          enum:
                            - sunday
                            - monday
                            - tuesday
                            - wednesday
                            - thursday
                            - friday
                            - saturday
                        startTime:
                          type: string
                          pattern: "^([01]?[0-9]|2[0-3]):[0-5][0-9]$"
                        durationHours:
                          type: integer
                          minimum: 1
                          maximum: 24

            status:
              type: object
              properties:
                clusterName:
                  type: string
                  description: "Actual cluster name in cloud provider"

                clusterArn:
                  type: string
                  description: "ARN/ID of the cluster"

                endpoint:
                  type: string
                  description: "Kubernetes API server endpoint"

                status:
                  type: string
                  description: "Current cluster status"

                nodeGroupsReady:
                  type: integer
                  description: "Number of ready node groups"

                totalNodes:
                  type: integer
                  description: "Total number of nodes"

                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string

      additionalPrinterColumns:
        - name: Provider
          type: string
          jsonPath: ".spec.cloudProvider"
        - name: Region
          type: string
          jsonPath: ".spec.region"
        - name: Environment
          type: string
          jsonPath: ".spec.environment"
        - name: K8s Version
          type: string
          jsonPath: ".spec.kubernetes.version"
        - name: Status
          type: string
          jsonPath: ".status.status"
        - name: Endpoint
          type: string
          jsonPath: ".status.endpoint"
          priority: 1
        - name: Age
          type: date
          jsonPath: ".metadata.creationTimestamp"

---
# Composite Resource Definition for Database
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatabases.platform.gitops.io
  annotations:
    description: "Cloud-agnostic database abstraction"
spec:
  group: platform.gitops.io
  names:
    kind: XDatabase
    plural: xdatabases
    shortNames:
      - xdb
    categories:
      - crossplane
      - platform
      - database

  claimNames:
    kind: Database
    plural: databases

  connectionSecretKeys:
    - endpoint
    - port
    - username
    - password
    - connectionString

  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - engine
                - cloudProvider
                - region
              properties:
                cloudProvider:
                  type: string
                  enum: [aws, gcp, azure]

                region:
                  type: string

                engine:
                  type: string
                  enum:
                    - postgres
                    - mysql
                    - mariadb
                  default: postgres

                engineVersion:
                  type: string
                  default: "15"

                instanceClass:
                  type: string
                  default: db.t3.medium

                storageGB:
                  type: integer
                  default: 100
                  minimum: 20

                multiAZ:
                  type: boolean
                  default: true

                backupRetentionDays:
                  type: integer
                  default: 7
                  minimum: 0
                  maximum: 35

                deletionProtection:
                  type: boolean
                  default: true

      additionalPrinterColumns:
        - name: Engine
          type: string
          jsonPath: ".spec.engine"
        - name: Version
          type: string
          jsonPath: ".spec.engineVersion"
        - name: Provider
          type: string
          jsonPath: ".spec.cloudProvider"
        - name: Age
          type: date
          jsonPath: ".metadata.creationTimestamp"
