---
# GCP Provider Installation
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp
  annotations:
    description: "GCP provider for Crossplane to manage Google Cloud resources"
spec:
  package: xpkg.upbound.io/upbound/provider-family-gcp:v1.0.0
  controllerConfigRef:
    name: gcp-controller-config

---
# GCP Provider Controller Configuration
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: gcp-controller-config
  annotations:
    description: "Controller configuration for GCP provider with Workload Identity"
spec:
  podSecurityContext:
    fsGroup: 2000
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000

  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: "500m"
      memory: 1Gi

  serviceAccountName: crossplane-provider-gcp

  args:
    - --debug
    - --max-reconcile-rate=50
    - --poll=1m

---
# GCP Provider Configuration (using Workload Identity)
apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: gcp-provider-config
spec:
  projectID: YOUR_GCP_PROJECT_ID
  credentials:
    source: InjectedIdentity

---
# ServiceAccount for GCP Provider (Workload Identity)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossplane-provider-gcp
  namespace: crossplane-system
  annotations:
    # Configure for GCP Workload Identity
    iam.gke.io/gcp-service-account: crossplane-provider@YOUR_PROJECT.iam.gserviceaccount.com

---
# Individual GCP Service Providers
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-compute
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-compute:v1.0.0
  controllerConfigRef:
    name: gcp-controller-config

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-container
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-container:v1.0.0
  controllerConfigRef:
    name: gcp-controller-config

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-sql
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-sql:v1.0.0
  controllerConfigRef:
    name: gcp-controller-config

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-storage
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-storage:v1.0.0
  controllerConfigRef:
    name: gcp-controller-config
