# Tenant RBAC Templates
# Applied to each tenant namespace during onboarding
# Variables: {{ .TenantName }}, {{ .Namespace }}
---
# Tenant Admin Role - Full access within tenant namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-admin
  namespace: "{{ .Namespace }}"
  labels:
    app.kubernetes.io/name: multi-tenant-platform
    app.kubernetes.io/component: rbac
    platform.devsecops.io/tenant: "{{ .TenantName }}"
    rbac.platform.devsecops.io/role: tenant-admin
rules:
  # Full access to workloads
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Pods and logs
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec", "pods/portforward"]
    verbs: ["get", "list", "watch", "create", "delete"]
  # Services
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # ConfigMaps and Secrets
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Persistent storage
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Service accounts
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Ingress
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # HPA
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Jobs and CronJobs
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Events
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  # Resource quotas (read-only)
  - apiGroups: [""]
    resources: ["resourcequotas", "limitranges"]
    verbs: ["get", "list", "watch"]
  # Network policies (read-only - platform controls these)
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch"]
  # Policy reports (read-only)
  - apiGroups: ["wgpolicyk8s.io"]
    resources: ["policyreports"]
    verbs: ["get", "list", "watch"]
  # Pod Disruption Budgets
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-admin-binding
  namespace: "{{ .Namespace }}"
  labels:
    app.kubernetes.io/name: multi-tenant-platform
    platform.devsecops.io/tenant: "{{ .TenantName }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-admin
subjects:
  - kind: Group
    name: "{{ .TenantName }}-admins"
    apiGroup: rbac.authorization.k8s.io
---
# Tenant Developer Role - Can deploy and manage workloads, limited secret access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-developer
  namespace: "{{ .Namespace }}"
  labels:
    app.kubernetes.io/name: multi-tenant-platform
    app.kubernetes.io/component: rbac
    platform.devsecops.io/tenant: "{{ .TenantName }}"
    rbac.platform.devsecops.io/role: tenant-developer
rules:
  # Workloads
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Pods
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec", "pods/portforward"]
    verbs: ["create"]
  # Services
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # ConfigMaps (full access)
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Secrets (read reference only, not content)
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  # PVCs
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "delete"]
  # Ingress
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # HPA
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Jobs
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
  # Events
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  # View quotas
  - apiGroups: [""]
    resources: ["resourcequotas", "limitranges"]
    verbs: ["get", "list", "watch"]
  # Policy reports
  - apiGroups: ["wgpolicyk8s.io"]
    resources: ["policyreports"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-developer-binding
  namespace: "{{ .Namespace }}"
  labels:
    app.kubernetes.io/name: multi-tenant-platform
    platform.devsecops.io/tenant: "{{ .TenantName }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-developer
subjects:
  - kind: Group
    name: "{{ .TenantName }}-developers"
    apiGroup: rbac.authorization.k8s.io
---
# Tenant Viewer Role - Read-only access to namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-viewer
  namespace: "{{ .Namespace }}"
  labels:
    app.kubernetes.io/name: multi-tenant-platform
    app.kubernetes.io/component: rbac
    platform.devsecops.io/tenant: "{{ .TenantName }}"
    rbac.platform.devsecops.io/role: tenant-viewer
rules:
  # View workloads
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["get", "list", "watch"]
  # View pods
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  # View services
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
  # View config
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  # View PVCs
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  # View ingress
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  # View HPA
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
  # View jobs
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  # View events
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  # View quotas
  - apiGroups: [""]
    resources: ["resourcequotas", "limitranges"]
    verbs: ["get", "list", "watch"]
  # View network policies
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch"]
  # View policy reports
  - apiGroups: ["wgpolicyk8s.io"]
    resources: ["policyreports"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-viewer-binding
  namespace: "{{ .Namespace }}"
  labels:
    app.kubernetes.io/name: multi-tenant-platform
    platform.devsecops.io/tenant: "{{ .TenantName }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-viewer
subjects:
  - kind: Group
    name: "{{ .TenantName }}-viewers"
    apiGroup: rbac.authorization.k8s.io
---
# CI/CD Service Account for tenant pipelines
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .TenantName }}-cicd"
  namespace: "{{ .Namespace }}"
  labels:
    app.kubernetes.io/name: multi-tenant-platform
    platform.devsecops.io/tenant: "{{ .TenantName }}"
    platform.devsecops.io/purpose: cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .TenantName }}-cicd-binding"
  namespace: "{{ .Namespace }}"
  labels:
    app.kubernetes.io/name: multi-tenant-platform
    platform.devsecops.io/tenant: "{{ .TenantName }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-developer
subjects:
  - kind: ServiceAccount
    name: "{{ .TenantName }}-cicd"
    namespace: "{{ .Namespace }}"
