# Tenant Network Isolation Policies
# Applied to each tenant namespace to prevent cross-tenant traffic
# Variables: {{ .TenantName }}, {{ .Namespace }}
---
# Default deny all ingress and egress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: "{{ .Namespace }}"
  labels:
    app.kubernetes.io/name: multi-tenant-platform
    app.kubernetes.io/component: network-policy
    platform.devsecops.io/tenant: "{{ .TenantName }}"
    platform.devsecops.io/policy-type: default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
# Allow intra-namespace communication
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace
  namespace: "{{ .Namespace }}"
  labels:
    app.kubernetes.io/name: multi-tenant-platform
    app.kubernetes.io/component: network-policy
    platform.devsecops.io/tenant: "{{ .TenantName }}"
    platform.devsecops.io/policy-type: intra-namespace
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - podSelector: {}
---
# Allow traffic from same tenant (cross-namespace within tenant)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-tenant
  namespace: "{{ .Namespace }}"
  labels:
    app.kubernetes.io/name: multi-tenant-platform
    app.kubernetes.io/component: network-policy
    platform.devsecops.io/tenant: "{{ .TenantName }}"
    platform.devsecops.io/policy-type: intra-tenant
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              platform.devsecops.io/tenant: "{{ .TenantName }}"
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              platform.devsecops.io/tenant: "{{ .TenantName }}"
---
# Allow DNS resolution (required for all pods)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: "{{ .Namespace }}"
  labels:
    app.kubernetes.io/name: multi-tenant-platform
    app.kubernetes.io/component: network-policy
    platform.devsecops.io/tenant: "{{ .TenantName }}"
    platform.devsecops.io/policy-type: dns
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    # CoreDNS in kube-system
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
# Allow ingress from ingress controller
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-controller
  namespace: "{{ .Namespace }}"
  labels:
    app.kubernetes.io/name: multi-tenant-platform
    app.kubernetes.io/component: network-policy
    platform.devsecops.io/tenant: "{{ .TenantName }}"
    platform.devsecops.io/policy-type: ingress-controller
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
---
# Allow metrics scraping from Prometheus
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-scrape
  namespace: "{{ .Namespace }}"
  labels:
    app.kubernetes.io/name: multi-tenant-platform
    app.kubernetes.io/component: network-policy
    platform.devsecops.io/tenant: "{{ .TenantName }}"
    platform.devsecops.io/policy-type: observability
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: 9090
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443
        # Common metrics ports
        - protocol: TCP
          port: 9100
        - protocol: TCP
          port: 9113
---
# Allow external HTTPS egress (for pulling images, API calls)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-https
  namespace: "{{ .Namespace }}"
  labels:
    app.kubernetes.io/name: multi-tenant-platform
    app.kubernetes.io/component: network-policy
    platform.devsecops.io/tenant: "{{ .TenantName }}"
    platform.devsecops.io/policy-type: external-egress
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              # Block internal cluster networks
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
---
# Allow access to platform services (observability, gitops)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-platform-services
  namespace: "{{ .Namespace }}"
  labels:
    app.kubernetes.io/name: multi-tenant-platform
    app.kubernetes.io/component: network-policy
    platform.devsecops.io/tenant: "{{ .TenantName }}"
    platform.devsecops.io/policy-type: platform-services
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    # Allow to platform-system namespace
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: platform-system
    # Allow to observability namespace for pushing logs/metrics
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
