---
# ArgoCD ApplicationSet for Fleet-Wide Application Deployment
# Uses generators to deploy applications across all clusters in the fleet

# Platform Tools ApplicationSet
# Deploys common platform tools to all clusters
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-tools
  namespace: argocd
spec:
  generators:
    # Cluster generator - deploy to all registered clusters
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
        values:
          revision: main

  template:
    metadata:
      name: '{{name}}-platform-tools'
      labels:
        app.kubernetes.io/name: platform-tools
        cluster: '{{name}}'
    spec:
      project: platform
      source:
        repoURL: https://github.com/YOUR_ORG/platform-config
        targetRevision: '{{values.revision}}'
        path: platform-tools/overlays/{{metadata.labels.environment}}
      destination:
        server: '{{server}}'
        namespace: platform-tools
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

---
# Observability Stack ApplicationSet
# Deploys monitoring stack to all clusters
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability-stack
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster

  template:
    metadata:
      name: '{{name}}-observability'
      labels:
        app.kubernetes.io/name: observability
        cluster: '{{name}}'
    spec:
      project: platform
      source:
        repoURL: https://github.com/YOUR_ORG/platform-config
        targetRevision: main
        path: observability/overlays/{{metadata.labels.environment}}
        helm:
          valueFiles:
            - values.yaml
            - values-{{metadata.labels.environment}}.yaml
      destination:
        server: '{{server}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

---
# Policy Engine ApplicationSet
# Deploys Kyverno and policies to all clusters
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: policy-engine
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster

  template:
    metadata:
      name: '{{name}}-kyverno'
      labels:
        app.kubernetes.io/name: kyverno
        cluster: '{{name}}'
    spec:
      project: security
      source:
        repoURL: https://github.com/YOUR_ORG/policies
        targetRevision: main
        path: kyverno/overlays/{{metadata.labels.environment}}
      destination:
        server: '{{server}}'
        namespace: kyverno
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true

---
# Sample Application - Deployed across environments
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-app
  namespace: argocd
spec:
  generators:
    # Matrix generator - combines clusters and environments
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
          - list:
              elements:
                - app: frontend
                  path: apps/frontend
                - app: backend
                  path: apps/backend
                - app: api-gateway
                  path: apps/api-gateway

  template:
    metadata:
      name: '{{name}}-{{app}}'
      labels:
        app.kubernetes.io/name: '{{app}}'
        cluster: '{{name}}'
        environment: '{{metadata.labels.environment}}'
    spec:
      project: applications
      source:
        repoURL: https://github.com/YOUR_ORG/applications
        targetRevision: main
        path: '{{path}}/overlays/{{metadata.labels.environment}}'
        kustomize:
          images:
            - 'registry.company.com/{{app}}:{{metadata.labels.environment}}'
      destination:
        server: '{{server}}'
        namespace: '{{app}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m

---
# Environment-Specific Application Deployment
# Uses Git Generator for PR-based deployments
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-environments
  namespace: argocd
spec:
  generators:
    # Pull Request Generator - create environments for PRs
    - pullRequest:
        github:
          owner: YOUR_ORG
          repo: applications
          tokenRef:
            secretName: github-token
            key: token
        requeueAfterSeconds: 60

  template:
    metadata:
      name: 'pr-{{number}}-{{branch_slug}}'
      labels:
        app.kubernetes.io/name: pr-environment
        pr-number: '{{number}}'
    spec:
      project: pr-environments
      source:
        repoURL: https://github.com/YOUR_ORG/applications
        targetRevision: '{{head_sha}}'
        path: deploy/pr
        kustomize:
          namePrefix: 'pr-{{number}}-'
          commonLabels:
            pr: '{{number}}'
      destination:
        server: https://kubernetes.default.svc  # Deploy to dev cluster
        namespace: 'pr-{{number}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

---
# Multi-Region Deployment ApplicationSet
# Deploys to specific regions based on labels
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: regional-apps
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          # Cluster generator filtered by region
          - clusters:
              selector:
                matchLabels:
                  environment: production
              values:
                region: '{{metadata.labels.region}}'
          # List of regional configurations
          - list:
              elements:
                - app: payment-service
                  regionalConfig: true
                - app: user-service
                  regionalConfig: true

  template:
    metadata:
      name: '{{name}}-{{app}}'
      labels:
        app.kubernetes.io/name: '{{app}}'
        cluster: '{{name}}'
        region: '{{values.region}}'
    spec:
      project: production
      source:
        repoURL: https://github.com/YOUR_ORG/applications
        targetRevision: main
        path: apps/{{app}}/overlays/{{values.region}}
        helm:
          valueFiles:
            - values.yaml
            - 'values-{{values.region}}.yaml'
      destination:
        server: '{{server}}'
        namespace: '{{app}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
